version: "3.6"

services:
  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=teamformationassistant
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpwd
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    networks:
      - application_network

  mocker:
    build:
      context: ./mocker
    container_name: mocker
    command: ["npm", "start"]
    depends_on:
      - database
    networks:
      - application_network

  node_server:
    build:
      context: ./backend
    container_name: node_server
    command: ["npm", "start"]
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - application_network

  ml_server:
    build:
      context: ./ml-service
    container_name: ml_server
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - mocker
    ports:
      - 5000:5000
    networks:
      - application_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: ["npm", "start"]
    depends_on:
      - node_server
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - application_network

volumes:
  db:

networks:
  application_network:
    driver: bridge
